name: Upload Release Asset when Tag is pushed

on:
  push:
    tags: 
      - '*' 

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into a workflow directory
        uses: actions/checkout@v2

      - name: Getting latest tag on the repo
        id: latest_tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true

      - name: Creating Artifact
        run: |
          sed -i 's/PLUGIN_VERSION/${{ steps.latest_tag.outputs.tag }}/' thank-after-post-plugin.php
          zip -r thank-after-post.zip . -x '*.git*'

      - name: Creating Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "thank-after-post.zip"
          name: Release ${{ steps.latest_tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
